### PR TITLE
Bugfix/nominal type normalization

### LINKED ISSUE #160: Misleading information in docs - List declaration
**Describe the bug**

I tried this code:

`
entrypoint function main(): List[Int] {
    var n: List[Int] = List@{1, 2, 3};
    return n;
}
`

**and was getting this message:** 
fail with exception -- TypeError: Cannot read property 'invoke' of undefined

**so I've added `[Int]` before declaring what is in list, like this:**

`
entrypoint function main(): List[Int] {
    var n: List[Int] = List[Int]@{1, 2, 3};
    return n;
}
`

and the code runs just fine.

**So couple of issues:**
1) Error message does not show in which line it occurs and what exactly should be done
2) There are errors in docs, like here:

image

or here:

image

Correct me if I'm wrong.

### PR DESCRIPTION
**Pull request by catchmareck**
Fixes #160 

   Changes:
Changed `normalizeType_Nominal()` method in `Assembly` class because without this check, later, the `normalizeType()` method was receiving `undefined` as `t: TypeSignature` which was resulting in treating `undefined` as `Union` type which was not correct.

Note:
Please review this change before merge because I am not 100% sure if it's correct. It throws `Bad signature error` now so I guess this is correct but some confirmation from the creators would be appreciated.

### CODE REVIEW

**Comment by mrkmarron** [comment]
Do you have a code snippet that demonstrates this issue?

**Comment by mrkmarron** [comment]
Looking in more detail I think the fix is to make sure that any template terms in the `fconcept`/`fobject` match a binding in the `aliasResolvedBinds` map.

**Comment by catchmareck** [comment]
Thanks for taking a look at this one @mrkmarron 

Are you thinking about something like this?

```
private bindsMatch(templateTerms: TemplateTermDecl[], resolvedBinds: Map<string, ResolvedType> ): boolean {
    
    for (let i = 0; i < templateTerms.length; i++) {
        const term = templateTerms[i];
        const exists = resolvedBinds.has(term.name);
        if (!exists) return false;
    }

    return true;
}
```
and then
```
if (!this.bindsMatch(fobject.terms, aliasResolvedBinds)) {
    return ResolvedType.createEmpty();
}
```
If yes, then the `Bad type signature` error is being thrown even for a valid code. This is because the `aliasResolvedBinds` map happens to be empty even for correctly resolved type, e.x.:

**main.bsq** (shortened):
```
var n: List[Int] = List[Int]@{1, 2, 3};
```
and if I put some debugging info in the `normalizeType_Nominal()` method, like this:
```
console.log(fobject.terms, aliasResolvedType, aliasResolvedBinds);
```
then this is printed in the output when run:
```
[ TemplateTermDecl {
    isUnique: false,
    name: 'T',
    ttype:
     NominalTypeSignature { nameSpace: 'NSCore', baseName: 'Any', terms: [] } } ]
NominalTypeSignature {
  nameSpace: 'NSCore',
  baseName: 'List',
  terms:
   [ NominalTypeSignature { nameSpace: 'NSCore', baseName: 'Int', terms: [] } ] }
Map {}
```
so looking for matching binding in the map is guaranteed failure. Should I look for the cause of the map being empty? Also, shouldn't `lookupTypeDef()` method be responsible for making sure if matching binding exists?

**Comment by mrkmarron** [comment]
You are right and your initial proposed fix is the correct one (since the `declterms`/`giventerms` are resolved pairwise in the `resolveTemplateBinds` code). Thanks for double checking and I'll merge your fix now.

**Pull request merged**
