### PR TITLE
Docs: code-style addition for Highlight Features category.

### PR DESCRIPTION
**Pull request by MairwunNx**
You can see preview changes in my cloned repo: https://github.com/MairwunNx/BosqueLanguage/blob/example-codestyle-docs/docs/language/overview.md

I wrote this documentation according to the code already written in the **BosqueLanguage** repository and already guided by the existing repetitions of the code style.

Documentation may not be complete, because the code is still very small, and there is no official documentation. I think it would not be bad for the first time to merge my documentation, so that novices or those who want to try a language would write a code according to the style.

### CODE REVIEW

**Comment by hearot** [comment]
Awesome! Just two things:

   1. I think that after a *statement keyword* there should be a blank space:

      - **Do:**

        ```js
        if (...) {
        }
        ```
      - **Don't:**

        ```js
        if(...) {
        }
        ```

   2. What about namespaces? As said in #85, their design has not been decided yet, but I think that all namespaces should start with an upper letter using *CamelCase*.

Do you agree with me? 😄

**Comment by MairwunNx** [comment]
@hearot 
1. Thank! Alas, I can not agree about the space after the if statement. I understand that the space is better and in many languages that way, but from the code that the microsoft guys wrote and from what is written in the documentation without a space, I came to the conclusion that i cannot put a space in the Bosque code style after the if statement. 😉

2. About namespaces: I don’t know much about them at all, I agree with you, and I think they should have CamelCase, but as long as I don’t know for sure, I think as soon as the information appears, I will update the documentation. 🤔🤔

**Comment by hearot** [comment]
We will see! 👍

**Comment by mrkmarron** [comment]
I like the proposal, will need to look at it more carefully though. 

In general I think the TypeScript formatting guidelines (as the autoformatter in Visual Studio Code) work pretty well and are a good basis for things.

**Comment by MairwunNx** [comment]
@mrkmarron Good. Consider my changes and if everything suits you accept
TypeScript formatter does not fit much, but do not forget that there is not a lot of different code style.

**Pull request merged**
