### PR TITLE
pretiffy code samples using js coloring

### PR DESCRIPTION
**Pull request by smoothdeveloper**
image

### CODE REVIEW

**Comment by menduz** [comment]
You can switch to ts to highlight the types

**Comment by hearot** [comment]
Awesome, but what about proposing Bosque to [linguist](https://github.com/github/linguist/)?

**Comment by smoothdeveloper** [comment]
@menduz good point, done.

@hearot: https://github.com/github/linguist/issues/4503

**Comment by hearot** [comment]
> @menduz good point, done.
> 
> @hearot: [github/linguist#4503](https://github.com/github/linguist/issues/4503)

Nice job! 👍

**Comment by mrkmarron** [comment]
I appreciate the PR but, as with issue #87, I am hesitant to use TS or JS highlighting as it may be misleading. Thanks for raising the issue with linguist, even if they are not going to act on it just yet. So, I am going to close this PR for the current time.

**Pull request closed without merging**
