### PR TITLE
Add separator to string concat

### PR DESCRIPTION
**Pull request by Xh4H**
Changes:
Adds a parameter to string concat to choose the separator.

```
namespace NSMain;

entrypoint function main(): Bool {
    _debug(String::concat(" ", "testing", "this")); // "testing this"
    return true;
}
```

IMO, it's a better design to choose the separator BEFORE dropping the string list to be concatenated.

### CODE REVIEW

**Comment by Xh4H** [comment]
IMO, it's a better design to choose the separator BEFORE dropping the string list to be concatenated.

**Comment by mrkmarron** [comment]
Do we want to modify the concat API or introduce a new method, say `join`, that takes a separator?

**Comment by liukun** [comment]
Too strange IMHO, it's common sense that

    String::concat(" ", "testing", "this")); // = " testingthis"

**Comment by Xh4H** [comment]
I mean, if this project is searching and testing every single way of development, I guess it could be worth a try?

**Comment by mrkmarron** [comment]
It looks like this PR has stalled. Feel free to reopen if/when we are ready to work on it again.

**Pull request closed without merging**
