### PR TITLE
Add two new examples

### PR DESCRIPTION
**Pull request by hearot**
I've added two new examples that show how easy to use Bosque is. There are features that you can't find in other languages (for example "ensures", my favourite).

This patch works fine with the build & test environment.

### CODE REVIEW

**Comment by hearot** [comment]
This closes #69 and #70.

**Comment by mrkmarron** [comment]
@hearot this looks great. Two small changes:
1. In the readme can we have links to both the max _and_ tictactoe example. I like the idea of having a simpler example but seeing a "slightly" larger chunk of code is useful as well.
2. I notice the code uses `var!` instead of just plain `var` but never re-assigns the variable. I would like to have the best practice be using the non-updateable `var` whenever possible.

If it is easy for you to make these changes (and you agree) please do so and I'll merge. Or, if you prefer, let me know and I can make them myself.

Thanks

**Comment by hearot** [comment]
I'm going to make these changes, don't worry! Thank you.

**Comment by mrkmarron** [comment]
Looks great. Thanks for the contributions.

**Pull request merged**
